### PR TITLE
Make it responsive #1

### PR DESCRIPTION
**Pull request by BoltUltra**
I have made it responsive for mobile view

### CODE REVIEW

**Review by vinitshahdeo — CHANGES_REQUESTED** [review]
Thanks for your contribution @BoltUltra 👏 

Can we please make the timer in a single row for the mobile view?  Also, the spacing can be reduced for the timer and `calling out mentors` section.

**Comment by BoltUltra** [comment]
> Thanks for your contribution @BoltUltra 👏
> 
> Can we please make the timer in a single row for the mobile view? Also, the spacing can be reduced for the timer and `calling out mentors` section.

Sure

**Comment by BoltUltra** [comment]
I have made the necessary changes as requested

**Review by vinitshahdeo — CHANGES_REQUESTED** [review]
@BoltUltra Thanks for the quick iteration. Appreciate it 👏 

The spacing still seems off in the mobile view, please check. The space between the timer and the `calling out mentors` section, buttons, and footer are kinda off. Please make it consistent for the mobile view.

**Review by vinitshahdeo — CHANGES_REQUESTED** [review]
Please check the mobile preview here: https://deploy-preview-2--50daysofjavascript.netlify.app/

Kindly fix the spacing accordingly.

Screenshot 2023-01-10 at 9 34 33 PM

**Comment by BoltUltra** [comment]
> @BoltUltra Thanks for the quick iteration. Appreciate it 👏
> 
> The spacing still seems off in the mobile view, please check. The space between the timer and the `calling out mentors` section, buttons, and footer are kinda off. Please make it consistent for the mobile view.

image
is this what you are seeing

**Comment by vinitshahdeo** [comment]
@BoltUltra If you closely the timer and the `calling out mentors` text are not aligned. Missing `justify-content: center` for timer component. Also the left margin for `calling out mentors`  can be removed. 

Please make these changes.

**Pull request merged**
